dim_x: 1
dim_y: 1
d_model: 64
emb_depth: 4
latent_dim_mult: 2
dim_feedforward: 128
nhead: 4
dropout: 0.0
num_layers: 2
H_A_dim: 32
use_H_A: False
num_induce: 16
num_spin_heads: 8
num_spin_blocks: 2
bound_std: False
